### ISSUE TITLE
Wrong number of arguments when staging up

### ISSUE THREAD

**Issue by emmahsax** [dispatchinc/ninny#13]
I got a strange error when trying to stage up a merge request when already on the staging branch:
```bash
$ ninny stage_up
/Users/emmasax/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/tty-prompt-0.18.1/lib/tty/prompt/choice.rb:80:in `initialize': wrong number of arguments (given 3, expected 2) (ArgumentError)
        from /Users/emmasax/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/tty-prompt-0.18.1/lib/tty/prompt/choice.rb:54:in `new'
        from /Users/emmasax/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/tty-prompt-0.18.1/lib/tty/prompt/choice.rb:54:in `convert_hash'
        from /Users/emmasax/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/tty-prompt-0.18.1/lib/tty/prompt/choice.rb:43:in `from'
        from /Users/emmasax/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/tty-prompt-0.18.1/lib/tty/prompt/choices.rb:68:in `<<'
        from /Users/emmasax/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/tty-prompt-0.18.1/lib/tty/prompt/list.rb:168:in `block in choices'
        from /Users/emmasax/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/tty-prompt-0.18.1/lib/tty/prompt/list.rb:168:in `each'
        from /Users/emmasax/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/tty-prompt-0.18.1/lib/tty/prompt/list.rb:168:in `choices'
        from /Users/emmasax/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/tty-prompt-0.18.1/lib/tty/prompt/list.rb:179:in `call'
        from /Users/emmasax/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/tty-prompt-0.18.1/lib/tty/prompt.rb:223:in `invoke_select'
        from /Users/emmasax/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/tty-prompt-0.18.1/lib/tty/prompt.rb:260:in `select'
        from /Users/emmasax/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ninny-0.1.15/lib/ninny/commands/pull_request_merge.rb:32:in `select_pull_request'
        from /Users/emmasax/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ninny-0.1.15/lib/ninny/commands/pull_request_merge.rb:23:in `execute'
        from /Users/emmasax/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ninny-0.1.15/lib/ninny/cli.rb:39:in `stage_up'
        from /Users/emmasax/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        from /Users/emmasax/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/emmasax/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        from /Users/emmasax/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
        from /Users/emmasax/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ninny-0.1.15/exe/ninny:15:in `<top (required)>'
        from /Users/emmasax/.rbenv/versions/3.0.0/bin/ninny:23:in `load'
        from /Users/emmasax/.rbenv/versions/3.0.0/bin/ninny:23:in `<main>'
```

It looks like the error is actually from TTY, but it'd be worth an investigation to see if it's something within the Ninny code.

**Comment by emmahsax** [comment]
It turns out this was a mixture of Ruby version 3.0.0, and a few changes in the Ninny code. We also needed to put in another catch.
